FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel

# RUN cat /etc/apt/sources.list \
#     && sed -i "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
#     && sed -i "s/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
#     && echo "\n" \
#     && cat /etc/apt/sources.list
