FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# RUN cat /etc/apt/sources.list \
#     && sed -i "s/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
#     && sed -i "s/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
#     && echo "\n" \
#     && cat /etc/apt/sources.list
